### ISSUE TITLE
Remove importtsys.py?

### ISSUE THREAD

**Issue by varenius** [jive-vlbi/casa-vlbi#5]
The file importtsys.py appears to overlap significantly with append_tsys.py functionality. But, importtsys.py does not have the fixes in 831143eaaa997c48acd13500a6f5c0b2bb9b7c25. What is the purpose of importtsys.py? Could it be removed?

**Comment by kettenis** [comment]
The importtsys.py script is useful to directly import Tsys measurements into a MeasurementSet, which can be useful for testing. It does indeed need some fixes.

**Comment by varenius** [comment]
Doesn't append_tsys.py do the same thing?
EDIT: No, I see, append_tsys is for FITS and importtsys if for MS, gotcha.

Still good to update the importtsys when possible.

**Comment by kettenis** [comment]
Finally got around to pushing some updates.
