### ISSUE TITLE
Crashing when 'opacity_corrected' is in POLY

### ISSUE THREAD

**Issue by bmarcote** [jive-vlbi/casa-vlbi#8]
At frequencies >~20 GHz (K band and above) some EVN antennas correct for atmospheric opacity. These antennas typically write in the ANTAB file this "feature" within the `POLY` parameter, e.g.:
```fortran
POLY = 0.7929185, 0.005900533, -4.203179e-05, opacity_corrected
```
When this line exists, `append_tsys` crashes as it (at the end) cannot parse the input into a float.

While reading the documentation of ANTAB in the NRAO/AIPS website, I have not found any reference to this being a standardized approach or not. I actually have not found any reference concerning opacity corrections in the ANTAB part at all.

In this sense I imagine two approaches:

1. It is considered a standard way and thus `append_tsys` should consider that it is a real possibility. In that sense ignoring such value would be fine (it has no effect in terms of the values that should be applied to the Tsys or GC).
2. It is not and thus the EVN should stop having such line in the archived ANTAB files.

**Comment by kettenis** [comment]
My opinion is very much #2. This EVN invention is a nightmare to support in code parsing ANTAB files.  The fact that AIPS silently ignores lots of random junk in ANTAB files isn't a good excuse.

If there is indeed a need to convey this information in some way to the user and/or software that reads ANTAB files, we should find a better way to add this information. Probably we should add a new keyword in the GAIN block to indicate whether gain curves have been opacity corrected or not. But we also have to think about what we should do with that information. There currently is no way to carry this information forward into FITS-IDI or the MeasurementSet and therefore AIPS and CASA cannot use this information.

P.S. I keep getting confused about what opacity corrected means in this context, i.e. whether it means the opacity effects have been removed from the data before the gain curve was fitted or not. But the gain curve is only part of the picture. It also matters whether the T_sys measurements are really T_sys or whether they actually are T_sys^*, i.e. whether the T_sys values themselves do not or do include opacity.

**Comment by kettenis** [comment]
Based on the discussion we had, can I close this issue?

**Comment by bmarcote** [comment]
Yes.
We will remove that unexpected flag from the archived ANTAB files from now on, and I will raise the issue to the stations.
Nothing to do with the code.
